from Bio.Seq import Seq
from Bio.Alphabet import IUPAC
import MySQLdb
import sys

mysql_host = 'karchin-hn02.icm.jhu.edu'
mysql_user = 'mryan'
mysql_password = 'royalenfield'
codontable_db = 'CHASM'
codontable_table = 'CodonTable'

db = MySQLdb.connect(host=mysql_host,\
                     user=mysql_user,\
                     passwd=mysql_password,\
                     db=codontable_db)
cursor = db.cursor()
reference_amino_acid_sequences_by_refseq = {
    'NM_014477.2':'MSPSAKKRPKNSRVSKMQDEKLRDETEQPVSKVIERNRLRTVLKNLSLLKLLKSSNRR'+\
                  'IQELHKLAKRCWHSLLSVPKILRISSGENSACNKTKQNNEEFQEIGCSEKELKSKKLE'+\
                  'STGDPKKKEYKEWKSQVQSGMRNKEKTSLAAMPRKEKHIEPEVPRTSRDDSLNPGVQG'+\
                  'RQPLTEGPRVIFIKPYRNRTPMGHMKQLDVADQWIWFEGLPTRIHLPAPRVMCRSSTL'+\
                  'RWVKRRCTRFCSASLEMPMWHPYKVDVTWTRARGASRGWRSRHQLKGRNGWRNSRVYK',
    'NM_004985.3':'MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDT'+\
                  'AGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHHYREQIKRVKDSEDVPMVLVGN'+\
                  'KCDLPSRTVDTKQAQDLARSYGIPFIETSAKTRQGVDDAFYTLVREIRKHKEKMSKDG'+\
                  'KKKKKKSKTKCVIM',
    'NM_016006.4':'MAAEEEEVDSADTGERSGWLTGWLPTWCPTSISHLKEAEEKMLKCVPCTYKKEPVRIS'+\
                  'NGNKIWTLKFSHNISNKTPLVLLHGFGGGLGLWALNFGDLCTNRPVYAFDLLGFGRSS'+\
                  'RPRFDSDAEEVENQFVESIEEWRCALGLDKMILLGHNLGGFLAAAYSLKYPSRVNHLI'+\
                  'LVEPWGFPERPDLADQDRPIPVWIRALGAALTPFNPLAGLRIAGPFGLSLVQRLRPDF'+\
                  'KRKYSSMFEDDTVTEYIYHCNVQTPSGETAFKNMTIPYGWAKRPMLQRIGKMHPDIPV'+\
                  'SVIFGARSCIDGNSGTSIQSLRPHSYVKTIAILGAGHYVYADQPEEFNQKVKEICDTVD',
    'NM_007355.2':'MPEEVHHGEEEVETFAFQAEIAQLMSLIINTFYSNKEIFLRELISNASDALDKIRYES'+\
                  'LTDPSKLDSGKELKIDIIPNPQERTLTLVDTGIGMTKADLINNLGTIAKSGTKAFMEA'+\
                  'LQAGADISMIGQFGVGFYSAYLVAEKVVVITKHNDDEQYAWESSAGGSFTVRADHGEP'+\
                  'IGRGTKVILHLKEDQTEYLEERRVKEVVKKHSQFIGYPITLYLEKEREKEISDDEAEE'+\
                  'EKGEKEEEDKDDEEKPKIEDVGSDEEDDSGKDKKKKTKKIKEKYIDQEELNKTKPIWT'+\
                  'RNPDDITQEEYGEFYKSLTNDWEDHLAVKHFSVEGQLEFRALLFIPRRAPFDLFENKK'+\
                  'KKNNIKLYVRRVFIMDSCDELIPEYLNFIRGVVDSEDLPLNISREMLQQSKILKVIRK'+\
                  'NIVKKCLELFSELAEDKENYKKFYEAFSKNLKLGIHEDSTNRRRLSELLRYHTSQSGD'+\
                  'EMTSLSEYVSRMKETQKSIYYITGESKEQVANSAFVERVRKRGFEVVYMTEPIDEYCV'+\
                  'QQLKEFDGKSLVSVTKEGLELPEDEEEKKKMEESKAKFENLCKLMKEILDKKVEKVTI'+\
                  'SNRLVSSPCCIVTSTYGWTANMERIMKAQALRDNSTMGYMMAKKHLEINPDHPIVETL'+\
                  'RQKAEADKNDKAVKDLVVLLFETALLSSGFSLEDPQTHSNRIYRMIKLGLGIDEDEVA'+\
                  'AEEPNAAVPDEIPPLEGDEDASRMEEVD',
    'NM_006599.3':'MPSDFISLLSADLDLESPKSLYSRESVYDLLPKELQLPPSRETSVASMSQTSGGEAGS'+\
                  'PPPAVVAADASSAPSSSSMGGACSSFTTSSSPTIYSTSVTDSKAMQVESCSSAVGVSN'+\
                  'RGVSEKQLTSNTVQQHPSTPKRHTVLYISPPPEDLLDNSRMSCQDEGCGLESEQSCSM'+\
                  'WMEDSPSNFSNMSTSSYNDNTEVPRKSRKRNPKQRPGVKRRDCEESNMDIFDADSAKA'+\
                  'PHYVLSQLTTDNKGNSKAGNGTLENQKGTGVKKSPMLCGQYPVKSEGKELKIVVQPET'+\
                  'QHRARYLTEGSRGSVKDRTQQGFPTVKLEGHNEPVVLQVFVGNDSGRVKPHGFYQACR'+\
                  'VTGRNTTPCKEVDIEGTTVIEVGLDPSNNMTLAVDCVGILKLRNADVEARIGIAGSKK'+\
                  'KSTRARLVFRVNIMRKDGSTLTLQTPSSPILCTQPAGVPEILKKSLHSCSVKGEEEVF'+\
                  'LIGKNFLKGTKVIFQENVSDENSWKSEAEIDMELFHQNHLIVKVPPYHDQHITLPVSV'+\
                  'GIYVVTNAGRSHDVQPFTYTPDPAAAGALNVNVKKEISSPARPCSFEEAMKAMKTTGC'+\
                  'NLDKVNIIPNALMTPLIPSSMIKSEDVTPMEVTAEKRSSTIFKTTKSVGSTQQTLENI'+\
                  'SNIAGNGSFSSPSSSHLPSENEKQQQIQPKAYNPETLTTIQTQDISQPGTFPAVSASS'+\
                  'QLPNSDALLQQATQFQTRETQSREILQSDGTVVNLSQLTEASQQQQQSPLQEQAQTLQ'+\
                  'QQISSNIFPSPNSVSQLQNTIQQLQAGSFTGSTASGSSGSVDLVQQVLEAQQQLSSVL'+\
                  'FSAPDGNENVQEQLSADIFQQVSQIQSGVSPGMFSSTEPTVHTRPDNLLPGRAESVHP'+\
                  'QSENTLSNQQQQQQQQQQVMESSAAMVMEMQQSICQAAAQIQSELFPSTASANGNLQQ'+\
                  'SPVYQQTSHMMSALSTNEDMQMQCELFSSPPAVSGNETSTTTTQQVATPGTTMFQTSS'+\
                  'SGDGEETGTQAKQIQNSVFQTMVQMQHSGDNQPQVNLFSSTKSMMSVQNSGTQQQGNG'+\
                  'LFQQGNEMMSLQSGNFLQQSSHSQAQLFHPQNPIADAQNLSQETQGSLFHSPNPIVHS'+\
                  'QTSTTSSEQMQPPMFHSQSTIAVLQGSSVPQDQQSTNIFLSQSPMNNLQTNTVAQEAF'+\
                  'FAAPNSISPLQSTSNSEQQAAFQQQAPISHIQTPMLSQEQAQPPQQGLFQPQVALGSL'+\
                  'PPNPMPQSQQGTMFQSQHSIVAMQSNSPSQEQQQQQQQQQQQQQQQQQSILFSNQNTM'+\
                  'ATMASPKQPPPNMIFNPNQNPMANQEQQNQSIFHQQSNMAPMNQEQQPMQFQSQSTVS'+\
                  'SLQNPGPTQSESSQTPLFHSSPQIQLVQGSPSSQEQQVTLFLSPASMSALQTSINQQD'+\
                  'MQQSPLYSPQNNMPGIQGATSSPQPQATLFHNTAGGTMNQLQNSPGSSQQTSGMFLFG'+\
                  'IQNNCSQLLTSGPATLPDQLMAISQPGQPQNEGQPPVTTLLSQQMPENSPLASSINTN'+\
                  'QNIEKIDLLVSLQNQGNNLTGSF',
    'NM_138714.3':'MGGACSSFTTSSSPTIYSTSVTDSKAMQVESCSSAVGVSNRGVSEKQLTSNTVQQHPS'+\
                  'TPKRHTVLYISPPPEDLLDNSRMSCQDEGCGLESEQSCSMWMEDSPSNFSNMSTSSYN'+\
                  'DNTEVPRKSRKRNPKQRPGVKRRDCEESNMDIFDADSAKAPHYVLSQLTTDNKGNSKA'+\
                  'GNGTLENQKGTGVKKSPMLCGQYPVKSEGKELKIVVQPETQHRARYLTEGSRGSVKDR'+\
                  'TQQGFPTVKLEGHNEPVVLQVFVGNDSGRVKPHGFYQACRVTGRNTTPCKEVDIEGTT'+\
                  'VIEVGLDPSNNMTLAVDCVGILKLRNADVEARIGIAGSKKKSTRARLVFRVNIMRKDG'+\
                  'STLTLQTPSSPILCTQPAGVPEILKKSLHSCSVKGEEEVFLIGKNFLKGTKVIFQENV'+\
                  'SDENSWKSEAEIDMELFHQNHLIVKVPPYHDQHITLPVSVGIYVVTNAGRSHDVQPFT'+\
                  'YTPDPAAAGALNVNVKKEISSPARPCSFEEAMKAMKTTGCNLDKVNIIPNALMTPLIP'+\
                  'SSMIKSEDVTPMEVTAEKRSSTIFKTTKSVGSTQQTLENISNIAGNGSFSSPSSSHLP'+\
                  'SENEKQQQIQPKAYNPETLTTIQTQDISQPGTFPAVSASSQLPNSDALLQQATQFQTR'+\
                  'ETQSREILQSDGTVVNLSQLTEASQQQQQSPLQEQAQTLQQQISSNIFPSPNSVSQLQ'+\
                  'NTIQQLQAGSFTGSTASGSSGSVDLVQQVLEAQQQLSSVLFSAPDGNENVQEQLSADI'+\
                  'FQQVSQIQSGVSPGMFSSTEPTVHTRPDNLLPGRAESVHPQSENTLSNQQQQQQQQQQ'+\
                  'VMESSAAMVMEMQQSICQAAAQIQSELFPSTASANGNLQQSPVYQQTSHMMSALSTNE'+\
                  'DMQMQCELFSSPPAVSGNETSTTTTQQVATPGTTMFQTSSSGDGEETGTQAKQIQNSV'+\
                  'FQTMVQMQHSGDNQPQVNLFSSTKSMMSVQNSGTQQQGNGLFQQGNEMMSLQSGNFLQ'+\
                  'QSSHSQAQLFHPQNPIADAQNLSQETQGSLFHSPNPIVHSQTSTTSSEQMQPPMFHSQ'+\
                  'STIAVLQGSSVPQDQQSTNIFLSQSPMNNLQTNTVAQEAFFAAPNSISPLQSTSNSEQ'+\
                  'QAAFQQQAPISHIQTPMLSQEQAQPPQQGLFQPQVALGSLPPNPMPQSQQGTMFQSQH'+\
                  'SIVAMQSNSPSQEQQQQQQQQQQQQQQQQQSILFSNQNTMATMASPKQPPPNMIFNPN'+\
                  'QNPMANQEQQNQSIFHQQSNMAPMNQEQQPMQFQSQSTVSSLQNPGPTQSESSQTPLF'+\
                  'HSSPQIQLVQGSPSSQEQQVTLFLSPASMSALQTSINQQDMQQSPLYSPQNNMPGIQG'+\
                  'ATSSPQPQATLFHNTAGGTMNQLQNSPGSSQQTSGMFLFGIQNNCSQLLTSGPATLPD'+\
                  'QLMAISQPGQPQNEGQPPVTTLLSQQMPENSPLASSINTNQNIEKIDLLVSLQNQGNNLTGSF',
    'NM_173214.2':'MGGACSSFTTSSSPTIYSTSVTDSKAMQVESCSSAVGVSNRGVSEKQLTSNTVQQHPSTPKRHTVLYISPPPEDLLDNSRMSCQDEGCGLESEQSCSMWMEDSPSNFSNMSTSSYNDNTEVPRKSRKRNPKQRPGVKRRDCEESNMDIFDADSAKAPHYVLSQLTTDNKGNSKAGNGTLENQKGTGVKKSPMLCGQYPVKSEGKELKIVVQPETQHRARYLTEGSRGSVKDRTQQGFPTVKLEGHNEPVVLQVFVGNDSGRVKPHGFYQACRVTGRNTTPCKEVDIEGTTVIEVGLDPSNNMTLAVDCVGILKLRNADVEARIGIAGSKKKSTRARLVFRVNIMRKDGSTLTLQTPSSPILCTQPAGVPEILKKSLHSCSVKGEEEVFLIGKNFLKGTKVIFQENVSDENSWKSEAEIDMELFHQNHLIVKVPPYHDQHITLPVSVGIYVVTNAGRSHDVQPFTYTPDPAAAGALNVNVKKEISSPARPCSFEEAMKAMKTTGCNLDKVNIIPNALMTPLIPSSMIKSEDVTPMEVTAEKRSSTIFKTTKSVGSTQQTLENISNIAGNGSFSSPSSSHLPSENEKQQQIQPKAYNPETLTTIQTQDISQPGTFPAVSASSQLPNSDALLQQATQFQTRETQSREILQSDGTVVNLSQLTEASQQQQQSPLQEQAQTLQQQISSNIFPSPNSVSQLQNTIQQLQAGSFTGSTASGSSGSVDLVQQVLEAQQQLSSVLFSAPDGNENVQEQLSADIFQQVSQIQSGVSPGMFSSTEPTVHTRPDNLLPGRAESVHPQSENTLSNQQQQQQQQQQVMESSAAMVMEMQQSICQAAAQIQSELFPSTASANGNLQQSPVYQQTSHMMSALSTNEDMQMQCELFSSPPAVSGNETSTTTTQQVATPGTTMFQTSSSGDGEETGTQAKQIQNSVFQTMVQMQHSGDNQPQVNLFSSTKSMMSVQNSGTQQQGNGLFQQGNEMMSLQSGNFLQQSSHSQAQLFHPQNPIADAQNLSQETQGSLFHSPNPIVHSQTSTTSSEQMQPPMFHSQSTIAVLQGSSVPQDQQSTNIFLSQSPMNNLQTNTVAQEAFFAAPNSISPLQSTSNSEQQAAFQQQAPISHIQTPMLSQEQAQPPQQGLFQPQVALGSLPPNPMPQSQQGTMFQSQHSIVAMQSNSPSQEQQQQQQQQQQQQQQQQQSILFSNQNTMATMASPKQPPPNMIFNPNQNPMANQEQQNQSIFHQQSNMAPMNQEQQPMQFQSQSTVSSLQNPGPTQSESSQTPLFHSSPQIQLVQGSPSSQEQQVTLFLSPASMSALQTSINQQDMQQSPLYSPQNNMPGIQGATSSPQPQATLFHNTAGGTMNQLQNSPGSSQQTSGMFLFGIQNNCSQLLTSGPATLPDQLMAISQPGQPQNEGQPPVTTLLSQQMPENSPLASSINTNQNIEKIDLLVSLQNQGNNLTGSF',
    'NM_173215.2':'MGGACSSFTTSSSPTIYSTSVTDSKAMQVESCSSAVGVSNRGVSEKQLTSNTVQQHPSTPKRHTVLYISPPPEDLLDNSRMSCQDEGCGLESEQSCSMWMEDSPSNFSNMSTSSYNDNTEVPRKSRKRNPKQRPGVKRRDCEESNMDIFDADSAKAPHYVLSQLTTDNKGNSKAGNGTLENQKGTGVKKSPMLCGQYPVKSEGKELKIVVQPETQHRARYLTEGSRGSVKDRTQQGFPTVKLEGHNEPVVLQVFVGNDSGRVKPHGFYQACRVTGRNTTPCKEVDIEGTTVIEVGLDPSNNMTLAVDCVGILKLRNADVEARIGIAGSKKKSTRARLVFRVNIMRKDGSTLTLQTPSSPILCTQPAGVPEILKKSLHSCSVKGEEEVFLIGKNFLKGTKVIFQENVSDENSWKSEAEIDMELFHQNHLIVKVPPYHDQHITLPVSVGIYVVTNAGRSHDVQPFTYTPDPAAAGALNVNVKKEISSPARPCSFEEAMKAMKTTGCNLDKVNIIPNALMTPLIPSSMIKSEDVTPMEVTAEKRSSTIFKTTKSVGSTQQTLENISNIAGNGSFSSPSSSHLPSENEKQQQIQPKAYNPETLTTIQTQDISQPGTFPAVSASSQLPNSDALLQQATQFQTRETQSREILQSDGTVVNLSQLTEASQQQQQSPLQEQAQTLQQQISSNIFPSPNSVSQLQNTIQQLQAGSFTGSTASGSSGSVDLVQQVLEAQQQLSSVLFSAPDGNENVQEQLSADIFQQVSQIQSGVSPGMFSSTEPTVHTRPDNLLPGRAESVHPQSENTLSNQQQQQQQQQQVMESSAAMVMEMQQSICQAAAQIQSELFPSTASANGNLQQSPVYQQTSHMMSALSTNEDMQMQCELFSSPPAVSGNETSTTTTQQVATPGTTMFQTSSSGDGEETGTQAKQIQNSVFQTMVQMQHSGDNQPQVNLFSSTKSMMSVQNSGTQQQGNGLFQQGNEMMSLQSGNFLQQSSHSQAQLFHPQNPIADAQNLSQETQGSLFHSPNPIVHSQTSTTSSEQMQPPMFHSQSTIAVLQGSSVPQDQQSTNIFLSQSPMNNLQTNTVAQEAFFAAPNSISPLQSTSNSEQQAAFQQQAPISHIQTPMLSQEQAQPPQQGLFQPQVALGSLPPNPMPQSQQGTMFQSQHSIVAMQSNSPSQEQQQQQQQQQQQQQQQQQSILFSNQNTMATMASPKQPPPNMIFNPNQNPMANQEQQNQSIFHQQSNMAPMNQEQQPMQFQSQSTVSSLQNPGPTQSESSQTPLFHSSPQIQLVQGSPSSQEQQVTLFLSPASMSALQTSINQQDMQQSPLYSPQNNMPGIQGATSSPQPQATLFHNTAGGTMNQLQNSPGSSQQTSGMFLFGIQNNCSQLLTSGPATLPDQLMAISQPGQPQNEGQPPVTTLLSQQMPENSPLASSINTNQNIEKIDLLVSLQNQGNNLTGSF',
    'NM_001113178.2':'MPSDFISLLSADLDLESPKSLYSRDSLKLHPSQNFHRAGLLEESVYDLLPKELQLPPSRETSVASMSQTSGGEAGSPPPAVVAADASSAPSSSSMGGACSSFTTSSSPTIYSTSVTDSKAMQVESCSSAVGVSNRGVSEKQLTSNTVQQHPSTPKRHTVLYISPPPEDLLDNSRMSCQDEGCGLESEQSCSMWMEDSPSNFSNMSTSSYNDNTEVPRKSRKRNPKQRPGVKRRDCEESNMDIFDADSAKAPHYVLSQLTTDNKGNSKAGNGTLENQKGTGVKKSPMLCGQYPVKSEGKELKIVVQPETQHRARYLTEGSRGSVKDRTQQGFPTVKLEGHNEPVVLQVFVGNDSGRVKPHGFYQACRVTGRNTTPCKEVDIEGTTVIEVGLDPSNNMTLAVDCVGILKLRNADVEARIGIAGSKKKSTRARLVFRVNIMRKDGSTLTLQTPSSPILCTQPAGVPEILKKSLHSCSVKGEEEVFLIGKNFLKGTKVIFQENVSDENSWKSEAEIDMELFHQNHLIVKVPPYHDQHITLPVSVGIYVVTNAGRSHDVQPFTYTPDPAAGALNVNVKKEISSPARPCSFEEAMKAMKTTGCNLDKVNIIPNALMTPLIPSSMIKSEDVTPMEVTAEKRSSTIFKTTKSVGSTQQTLENISNIAGNGSFSSPSSSHLPSENEKQQQIQPKAYNPETLTTIQTQDISQPGTFPAVSASSQLPNSDALLQQATQFQTRETQSREILQSDGTVVNLSQLTEASQQQQQSPLQEQAQTLQQQISSNIFPSPNSVSQLQNTIQQLQAGSFTGSTASGSSGSVDLVQQVLEAQQQLSSVLFSAPDGNENVQEQLSADIFQQVSQIQSGVSPGMFSSTEPTVHTRPDNLLPGRAESVHPQSENTLSNQQQQQQQQQQVMESSAAMVMEMQQSICQAAAQIQSELFPSTASANGNLQQSPVYQQTSHMMSALSTNEDMQMQCELFSSPPAVSGNETSTTTTQQVATPGTTMFQTSSSGDGEETGTQAKQIQNSVFQTMVQMQHSGDNQPQVNLFSSTKSMMSVQNSGTQQQGNGLFQQGNEMMSLQSGNFLQQSSHSQAQLFHPQNPIADAQNLSQETQGSLFHSPNPIVHSQTSTTSSEQMQPPMFHSQSTIAVLQGSSVPQDQQSTNIFLSQSPMNNLQTNTVAQEAFFAAPNSISPLQSTSNSEQQAAFQQQAPISHIQTPMLSQEQAQPPQQGLFQPQVALGSLPPNPMPQSQQGTMFQSQHSIVAMQSNSPSQEQQQQQQQQQQQQQQQQQSILFSNQNTMATMASPKQPPPNMIFNPNQNPMANQEQQNQSIFHQQSNMAPMNQEQQPMQFQSQSTVSSLQNPGPTQSESSQTPLFHSSPQIQLVQGSPSSQEQQVTLFLSPASMSALQTSINQQDMQQSPLYSPQNNMPGIQGATSSPQPQATLFHNTAGGTMNQLQNSPGSSQQTSGMFLFGIQNNCSQLLTSGPATLPDQLMAISQPGQPQNEGQPPVTTLLSQQMPENSPLASSINTNQNIEKIDLLVSLQNQGNNLTGSF',
    'NM_145239.2':'MAASSSEISEMKGVEESPKVPGEGPGHSEAETGPPQVLAGVPDQPEAPQPGPNTTAAP'+\
                  'VDSGPKAGLAPETTETPAGASETAQATDLSLSPGGESKANCSPEDPCQETVSKPEVSK'+\
                  'EATADQGSRLESAAPPEPAPEPAPQPDPRPDSQPTPKPALQPELPTQEDPTPEILSES'+\
                  'VGEKQENGAVVPLQAGDGEEGPAPEPHSPPSKKSPPANGAPPRVLQQLVEEDRMRRAH'+\
                  'SGHPGSPRGSLSRHPSSQLAGPGVEGGEGTQKPRDYIILAILSCFCPMWPVNIVAFAY'+\
                  'AVMSRNSLQQGDVDGAQRLGRVAKLLSIVALVGGVLIIIASCVINLGVYK'}

#for pos in xrange(69598997,69738553,100):
#    stmt = 'select mrnaAcc, codon, chrom, pos1, pos2, pos3, bases from '+\
#           codontable_table+' where chrom="chr16" and '+\
#           '(pos1='+str(pos)+' or pos2='+str(pos)+' or pos3='+str(pos)+')'
##    print stmt
#    cursor.execute(stmt)
#    result = cursor.fetchone()
#    print pos,result
#sys.exit()

for mrnaAcc in reference_amino_acid_sequences_by_refseq.keys():
    reference_amino_acid_sequence = reference_amino_acid_sequences_by_refseq[mrnaAcc]
    stmt = 'select codon, bases from '+codontable_table+' where mrnaAcc="'+mrnaAcc+'"'
#    print stmt
    cursor.execute(stmt)
    results = cursor.fetchall()
    codon_map = {}
    amino_acid_map = {}
    for result in results:
        (amino_acid_number, codon) = result
        amino_acid_number = int(amino_acid_number)
        codon_map[amino_acid_number] = codon
        amino_acid = Seq(codon, IUPAC.unambiguous_dna).translate()[0]
        amino_acid_map[amino_acid_number] = amino_acid
    amino_acid_numbers = amino_acid_map.keys()
    amino_acid_numbers.sort()
    amino_acid_sequence_from_codontable = ''
    for amino_acid_number in amino_acid_numbers:
        amino_acid_sequence_from_codontable += amino_acid_map[amino_acid_number]
    amino_acid_sequence_from_codontable = amino_acid_sequence_from_codontable.strip('*') # Removes '*' for the termination codon
    if amino_acid_sequence_from_codontable == reference_amino_acid_sequence:
        print mrnaAcc,'amino acid sequence match'
    else:
        print mrnaAcc,'amino acid sequence mismatch'
        print 'reference:',reference_amino_acid_sequence
        print 'retrieved:',amino_acid_sequence_from_codontable